<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 1 - Claudia

## Import `music_videos.ndjson` into a DataFrame

In [2]:
import pandas as pd
df_music_videos = pd.read_json("corpus/00_sources/music_videos.ndjson", lines=True)

df_music_videos

,id,url,title,description,language,uploader,duration,upload_date,error
0,4xqo7D2k8HM,https://www.youtube.com/watch?v=4xqo7D2k8HM,Imagine Dragons - Believer (Live in Vegas),Watch Imagine Dragons Live in Vegas on Hulu: \...,NaN,ImagineDragons,280.0,20230720.0,NaN
1,nyuo9-OjNNg,https://www.youtube.com/watch?v=nyuo9-OjNNg,I Wanna Be Yours,Provided to YouTube by Domino\n\nI Wanna Be Yo...,NaN,Official Arctic Monkeys,184.0,20141209.0,NaN
2,mRD0-GxqHVo,https://www.youtube.com/watch?v=mRD0-GxqHVo,Glass Animals - Heat Waves (Official Video),I LOVE YOU SO F***ING MUCH.\nOur fourth studio...,NaN,Glass Animals,235.0,20200629.0,NaN
3,V1Pl8CzNzCw,https://www.youtube.com/watch?v=V1Pl8CzNzCw,"Billie Eilish, Khalid - lovely",Listen to “lovely” (with Khalid): http://smart...,NaN,Billie Eilish,201.0,20180426.0,NaN
4,yKNxeF4KMsY,https://www.youtube.com/watch?v=yKNxeF4KMsY,Coldplay - Yellow (Official Video),Coldplay's tenth studio album Moon Music avail...,NaN,Coldplay,272.0,20110530.0,NaN
...,...,...,...,...,...,...,...,...,...
991,R7UrFYvl5TE,https://www.youtube.com/watch?v=R7UrFYvl5TE,Kelly Clarkson - Since U Been Gone (Official V...,"""Since U Been Gone"" performed by Kelly Clarkso...",NaN,Kelly Clarkson,192.0,20100928.0,NaN
992,4fndeDfaWCg,https://www.youtube.com/watch?v=4fndeDfaWCg,Backstreet Boys - I Want It That Way (Official...,"Official music video for ""I Want It That Way"" ...",NaN,Backstreet Boys,219.0,20091025.0,NaN
993,NaN,https://www.youtube.com/watch?v=plcmqP3b-Qg,NaN,NaN,NaN,NaN,NaN,NaN,ERROR: [youtube] plcmqP3b-Qg: Video...
994,xFrGuyw1V8s,https://www.youtube.com/watch?v=xFrGuyw1V8s,ABBA - Dancing Queen (Official Music Video),REMASTERED IN HD – UP TO 4K!!\n\nListen to mor...,NaN,ABBA,233.0,20091008.0,NaN
995,eH3giaIzONA,https://www.youtube.com/watch?v=eH3giaIzONA,Whitney Houston - I Wanna Dance With Somebody ...,Official Video for ”I Wanna Dance With Somebod...,NaN,Whitney Houston,314.0,20091025.0,NaN

## Replace the `error` column with a boolean indicating whether the video is available

In [4]:
# df_music_videos_dataset
df_music_videos_dataset = df_music_videos.copy()
df_music_videos_dataset['available'] = df_music_videos_dataset['error'].isna()
df_music_videos_dataset = df_music_videos_dataset.drop(columns=['error'])
df_music_videos_dataset

,id,url,title,description,language,uploader,duration,upload_date,available
0,4xqo7D2k8HM,https://www.youtube.com/watch?v=4xqo7D2k8HM,Imagine Dragons - Believer (Live in Vegas),Watch Imagine Dragons Live in Vegas on Hulu: \...,NaN,ImagineDragons,280.0,20230720.0,True
1,nyuo9-OjNNg,https://www.youtube.com/watch?v=nyuo9-OjNNg,I Wanna Be Yours,Provided to YouTube by Domino\n\nI Wanna Be Yo...,NaN,Official Arctic Monkeys,184.0,20141209.0,True
2,mRD0-GxqHVo,https://www.youtube.com/watch?v=mRD0-GxqHVo,Glass Animals - Heat Waves (Official Video),I LOVE YOU SO F***ING MUCH.\nOur fourth studio...,NaN,Glass Animals,235.0,20200629.0,True
3,V1Pl8CzNzCw,https://www.youtube.com/watch?v=V1Pl8CzNzCw,"Billie Eilish, Khalid - lovely",Listen to “lovely” (with Khalid): http://smart...,NaN,Billie Eilish,201.0,20180426.0,True
4,yKNxeF4KMsY,https://www.youtube.com/watch?v=yKNxeF4KMsY,Coldplay - Yellow (Official Video),Coldplay's tenth studio album Moon Music avail...,NaN,Coldplay,272.0,20110530.0,True
...,...,...,...,...,...,...,...,...,...
991,R7UrFYvl5TE,https://www.youtube.com/watch?v=R7UrFYvl5TE,Kelly Clarkson - Since U Been Gone (Official V...,"""Since U Been Gone"" performed by Kelly Clarkso...",NaN,Kelly Clarkson,192.0,20100928.0,True
992,4fndeDfaWCg,https://www.youtube.com/watch?v=4fndeDfaWCg,Backstreet Boys - I Want It That Way (Official...,"Official music video for ""I Want It That Way"" ...",NaN,Backstreet Boys,219.0,20091025.0,True
993,NaN,https://www.youtube.com/watch?v=plcmqP3b-Qg,NaN,NaN,NaN,NaN,NaN,NaN,False
994,xFrGuyw1V8s,https://www.youtube.com/watch?v=xFrGuyw1V8s,ABBA - Dancing Queen (Official Music Video),REMASTERED IN HD – UP TO 4K!!\n\nListen to mor...,NaN,ABBA,233.0,20091008.0,True
995,eH3giaIzONA,https://www.youtube.com/watch?v=eH3giaIzONA,Whitney Houston - I Wanna Dance With Somebody ...,Official Video for ”I Wanna Dance With Somebod...,NaN,Whitney Houston,314.0,20091025.0,True

## Export `df_music_videos_dataset` into NDJSON, TSV and XLSX formats

In [5]:
df_music_videos_dataset.to_json('corpus/00_sources/music_videos_dataset.ndjson', orient='records', lines=True)
df_music_videos_dataset.to_csv('corpus/00_sources/music_videos_dataset.tsv', sep='	', index=False)
df_music_videos_dataset.to_excel('corpus/00_sources/music_videos_dataset.xlsx', index=False)